### ISSUE TITLE
Performance evaluation

### ISSUE THREAD

**Issue by quejinhao** [Armilius/PISTE#2]
Why is the performance of PISTE on GitHub lower than the performance of PISTE on CodeOcean?

**Comment by ziyanfeng686** [comment]
Thank you very much for raising the issue. Upon inspection, we found that two lines of code were missing in the model file on GitHub. We have corrected the file.

**Comment by quejinhao** [comment]
Thank you for your response. I have retested the code, and the issue has been resolved.
