### ISSUE TITLE
Missing negative test data?

### ISSUE THREAD

**Issue by arosenfeld** [Armilius/PISTE#4]
Hello,

I'm trying to recreate Fig 2(a) which is described as:

"Figure 2a shows the results of random-shuffling negative sampling"

I see the positive data in [data/raw_data](https://github.com/Armilius/PISTE/tree/main/data/raw_data) but can't seem to find the negative data which seems to be referenced in [code/prepare_data.sh](https://github.com/Armilius/PISTE/blob/main/code/prepare_data.sh).

Am I missing this or was it not checked into the repo?

Thanks!

**Comment by ziyanfeng686** [comment]
Hello,

Thank you for your question!

The negative data is not pre-generated or explicitly included in the repository. Instead, it is dynamically created during the execution of the code/prepare_data.sh script. Specifically, the script generates the negative samples by performing random shuffling or mismatching of the positive data.

Once the script runs successfully, the generated negative data will be saved in the data/raw_data directory alongside the positive data.

If you have already run the code/prepare_data.sh script, you should see the negative samples in the specified folder. If not, please ensure the script runs without issues to generate the necessary files.

Let me know if you have further questions or encounter any issues!

**Comment by arosenfeld** [comment]
The prepare_data.sh script works and generates the negative data.

Thanks for the clarification!

**Comment by gmnnnhh** [comment]
Hello, I really appreciate your work! 
Could you please clarify whether the negative samples provided in your GitHub code for the test set are based on Test_1 or Test _2? If I choose to dynamically generate negative samples, how can I ensure a fair comparison with the results you reported? 
Thank you!
